export { default as Reservation } from "../pages/Reservation/Reservation"
export { default as Chefs } from "../pages/Chefs/Chefs"
export { default as Footer } from "../pages/Footer/Footer"
export { default as Menu } from "../pages/Menu/Menu"
export { default as Navbar } from "../pages/Navbar/Navbar"
