export { default as Home } from "../pages/Home/Home";
export { default as Chefs } from "../pages/Chefs/Chefs";
export { default as Footer } from "../pages/Footer/Footer";
export { default as Menu } from "../pages/Menu/Menu";
export { default as Navbar } from "../pages/Navbar/Navbar";
export { default as Header } from "../../src/pages/Header/Header";
export { default as MenuView } from "../pages/MenuView/MenuView";
export { default as About } from "../pages/About/About";
export { default as Testimonials } from "../pages/Testimonials/Testimonials";
export { default as Offer } from "../pages/Offer/Offer";
export { default as Booking } from '../pages/Booking/Booking'
export { default as Contact } from '../pages/Contact/Contact'